### ISSUE TITLE
Where to use React Credit Cards?

### ISSUE THREAD

**Issue by gleidsonh** [amarofashion/react-credit-cards#58]
I am trying to use with Stripe, but they said [here](https://github.com/stripe/react-stripe-elements/issues/228#issuecomment-522034125) it is not possible because of PCI compliance.

However, I really want to use React Credit Cards. Is there anyway to do that on Stripe? If don't, which payment gateway is allowed?

**Comment by gilbarbara** [comment]
Hello,

Yeah, this component can't be used with a PCI compliant setup since it uses the card number to identify the issuer. I can't say which gateways would work with it.

Anyway, I can't think in a generic approach to support multiple payment gateways since each one has its own way to handle input and encryption...
I've implemented a similar component with Adyen's Secure Fields but it was custom made.
